### ISSUE TITLE
Crash caused by missing Dbase folder

### ISSUE THREAD

**Issue by fizzle77** [51st-Vfw/JAFDTC#1]
Trivially fixed by manually creating the folder, but thought you'd want to know after a clean install I would  get this crash every time I tried to edit a waypoint.

1.0.0-B.28 of 8-APR-24 (build 6.670302)

```
==== JAFDTC version 1.0.0-B.28 of 8-APR-24 (build 6.670302) launched
Loaded settings
Loaded A-10C f28cb732-04fd-4049-a870-c075d9e6f143 'test' from 'test.json'
App:App Unhandled exception: 


App:App Unhandled exception: Could not find a part of the path 'C:\Users\<User>\Documents\JAFDTC\Dbase'.

   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at System.IO.Directory.GetFiles(String path)
   at JAFDTC.Utilities.FileManager.LoadPointsOfInterest() in C:\Users\twillis\Documents\GitHub\JAFDTC\JAFDTC\Utilities\FileManager.cs:line 432
   at JAFDTC.Models.DCS.PointOfInterestDbase.Reset() in C:\Users\twillis\Documents\GitHub\JAFDTC\JAFDTC\Models\DCS\PointOfInterestDbase.cs:line 381
   at JAFDTC.Models.DCS.PointOfInterestDbase..ctor() in C:\Users\twillis\Documents\GitHub\JAFDTC\JAFDTC\Models\DCS\PointOfInterestDbase.cs:line 132
   at JAFDTC.Models.DCS.PointOfInterestDbase.<>c.<.cctor>b__16_0() in C:\Users\twillis\Documents\GitHub\JAFDTC\JAFDTC\Models\DCS\PointOfInterestDbase.cs:line 108
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at JAFDTC.UI.Base.NavpointUIHelper.RebuildPointsOfInterest(PoIFilterSpec spec, String name) in C:\Users\twillis\Documents\GitHub\JAFDTC\JAFDTC\UI\Base\NavpointUIHelper.cs:line 140
   at JAFDTC.UI.Base.EditNavpointPage.RebuildPointsOfInterest() in C:\Users\twillis\Documents\GitHub\JAFDTC\JAFDTC\UI\Base\EditNavpointPage.xaml.cs:line 279
   at JAFDTC.UI.Base.EditNavpointPage.OnNavigatedTo(NavigationEventArgs args) in C:\Users\twillis\Documents\GitHub\JAFDTC\JAFDTC\UI\Base\EditNavpointPage.xaml.cs:line 626
   at Microsoft.UI.Xaml.Controls.Page.Microsoft.UI.Xaml.Controls.IPageOverrides.OnNavigatedTo(NavigationEventArgs e)
   at ABI.Microsoft.UI.Xaml.Controls.IPageOverrides.Do_Abi_OnNavigatedTo_1(IntPtr thisPtr, IntPtr e)
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.Controls.IFrameMethods.Navigate(IObjectReference _obj, Type sourcePageType, Object parameter, NavigationTransitionInfo infoOverride)
   at Microsoft.UI.Xaml.Controls.Frame.Navigate(Type sourcePageType, Object parameter, NavigationTransitionInfo infoOverride)
   at JAFDTC.UI.Base.EditNavpointListPage.EditNavpoint(INavpointInfo navpt) in C:\Users\twillis\Documents\GitHub\JAFDTC\JAFDTC\UI\Base\EditNavpointListPage.xaml.cs:line 142
   at JAFDTC.UI.Base.EditNavpointListPage.CmdOpen_Click(Object sender, RoutedEventArgs args) in C:\Users\twillis\Documents\GitHub\JAFDTC\JAFDTC\UI\Base\EditNavpointListPage.xaml.cs:line 256
   at WinRT._EventSource_global__Microsoft_UI_Xaml_RoutedEventHandler.EventState.<GetEventInvoke>b__1_0(Object sender, RoutedEventArgs e)
   at ABI.Microsoft.UI.Xaml.RoutedEventHandler.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr e)
==== JAFDTC version 1.0.0-B.28 of 8-APR-24 (build 6.670302) launched
Loaded settings
Loaded A-10C f28cb732-04fd-4049-a870-c075d9e6f143 'test' from 'test.json'
```

**Comment by ilominar** [comment]
Fixed in B.30.
