### ISSUE TITLE
Crash when sorting preset list with modulation

### ISSUE THREAD

**Issue by fizzle77** [51st-Vfw/JAFDTC#18]
On a radio with selectable modulation, if you set a preset number in a way that triggers the list of presets to sort, you get a crash:

```
App:App Unhandled exception: Value does not fall within the expected range.

   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.Controls.Primitives.ISelectorMethods.set_SelectedIndex(IObjectReference _obj, Int32 value)
   at Microsoft.UI.Xaml.Controls.Primitives.Selector.set_SelectedIndex(Int32 value)
   at JAFDTC.UI.Base.EditRadioPage.XamlBindingSetters.Set_Microsoft_UI_Xaml_Controls_Primitives_Selector_SelectedIndex(Selector obj, Int32 value)
   at JAFDTC.UI.Base.EditRadioPage.EditRadioPage_obj16_Bindings.Update_ModulationIndex(Int32 obj, Int32 phase)
   at JAFDTC.UI.Base.EditRadioPage.EditRadioPage_obj16_Bindings.Update_(RadioPresetItem obj, Int32 phase)
   at JAFDTC.UI.Base.EditRadioPage.EditRadioPage_obj16_Bindings.ProcessBindings(Object item, Int32 itemIndex, Int32 phase, Int32& nextPhase)
   at ABI.Microsoft.UI.Xaml.Markup.IDataTemplateComponent.Do_Abi_ProcessBindings_1(IntPtr thisPtr, IntPtr item, Int32 itemIndex, Int32 phase, Int32* nextPhase)
```

I spent some time trying to figure out a fix without success. Notably this looks like an exception resulting from a bad HRESULT in native code, being thrown down in a native/managed interop layer I can't debug. Running in the debugger and reproducing the crash, it doesn't helpfully halt in managed code, and the WPF binding stuff seems like a lot of behind-the-curtain magic. Slick when it works. Impenetrable when it doesn't.

The stack trace doesn't make this clear: the crash occurs in [this call to `EditPresets.Move()`](https://github.com/51st-Vfw/JAFDTC/blob/aaba892f79e9b748ea87554ca31a69103df69969/JAFDTC/UI/Base/EditRadioPage.xaml.cs#L476).

**Comment by ilominar** [comment]
Yeah, looks like a gnarly interaction between ListView, Move, and bindings. Near as I can tell, there's something going on with the bind on ModulationIndex that sets the selected item in the modulation ComboBox for a preset. Seems to work if I remove just that binding in the xaml. But no idea yet what exactly is coming off the rails as bindings are so bloody opaque.

May look into a non-binding-based implementation.

**Comment by ilominar** [comment]
Fixed. The basic non-binding-based implementation ran into similar issues. Found a hack that seems to work.

https://github.com/51st-Vfw/JAFDTC/commit/8351cb4a882bda1c1995bc6214582075ddc5d1f3
