### ISSUE TITLE
Crash on Launch Following Update

### ISSUE THREAD

**Issue by ilominar** [51st-Vfw/JAFDTC#37]
There is a collision in async dialogs at launch, causing crash (likely due to version splash colliding with Lua update).

```
App:App Unhandled exception: An async operation was not properly started.

Only a single ContentDialog can be open at any time.

   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.Controls.IContentDialogMethods.ShowAsync(IObjectReference _obj, ContentDialogPlacement placement)
   at Microsoft.UI.Xaml.Controls.ContentDialog.ShowAsync(ContentDialogPlacement placement)
   at JAFDTC.UI.Utilities.Message1BDialog(XamlRoot root, String title, String message, String button) in C:\Users\twillis\Documents\GitHub\JAFDTC\JAFDTC\UI\Utilities.cs:line 58
   at JAFDTC.UI.App.MainWindow.AppContentFrame_Loaded(Object sender, RoutedEventArgs args) in C:\Users\twillis\Documents\GitHub\JAFDTC\JAFDTC\UI\App\MainWindow.xaml.cs:line 305
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
```

**Comment by ilominar** [comment]
Fixed https://github.com/51st-Vfw/JAFDTC/commit/ed21d7515c4599d0303eb5bd66071fb6cf170b86 and the immediately preceding commit.
